"""Writes Gradle project files (Kotlin DSL / .kts). Ported from GradleBuildFiles.swift.

Swift-specific tasks (SwiftPM build / copy / Swift activity) are intentionally
omitted — generated projects are pure AGP."""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

from ..pyproject_toml import KivySchoolData

Arch = KivySchoolData.AndroidData.Arch


class GradleBuildError(Exception):
    pass


class GradleBuildFiles:

    # -------------------------------------------------------------------------
    # Root project files
    # -------------------------------------------------------------------------

    @staticmethod
    def write_root_build_gradle(dir: Path) -> None:
        content = """\
// Top-level build file - generated by ksproject
plugins {
    id("com.android.application") version "8.9.0" apply false
}
"""
        (dir / "build.gradle.kts").write_text(content)

    @staticmethod
    def write_settings_gradle(dir: Path, app_name: str) -> None:
        content = f"""\
pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
        google()
        mavenCentral()
    }}
}}

rootProject.name = "{app_name}"
include(":app")
"""
        (dir / "settings.gradle.kts").write_text(content)

    @staticmethod
    def write_gradle_properties(dir: Path) -> None:
        content = """\
# Project-wide Gradle settings - generated by ksproject
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
"""
        (dir / "gradle.properties").write_text(content)

    @staticmethod
    def write_local_properties(dir: Path, sdk_path: str) -> None:
        (dir / "local.properties").write_text(f"sdk.dir={sdk_path}\n")

    # -------------------------------------------------------------------------
    # Gradle wrapper
    # -------------------------------------------------------------------------

    @staticmethod
    def write_gradle_wrapper(dir: Path, java_path: str) -> None:
        wrapper_dir = dir / "gradle" / "wrapper"
        wrapper_dir.mkdir(parents=True, exist_ok=True)

        properties = """\
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-9.5.0-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""
        (wrapper_dir / "gradle-wrapper.properties").write_text(properties)

        jar_path = wrapper_dir / "gradle-wrapper.jar"
        if jar_path.exists():
            return

        print("[ksproject] Generating Gradle wrapper (requires system gradle)...")
        env = os.environ.copy()
        env["JAVA_HOME"] = java_path
        result = subprocess.run(
            ["gradle", "wrapper", "--gradle-version", "9.5.0"],
            cwd=dir,
            env=env,
        )
        if result.returncode != 0:
            raise GradleBuildError(
                f"gradle wrapper generation exited with code {result.returncode}"
            )

    # -------------------------------------------------------------------------
    # App module
    # -------------------------------------------------------------------------

    @staticmethod
    def write_app_build_gradle(
        app_dir: Path,
        package_name: str,
        archs: list[Arch],
        compile_sdk: int = 35,
        min_sdk: int = 24,
        target_sdk: int = 35,
        python_version: str = "3.13",
    ) -> None:
        (app_dir / "build.gradle.kts").write_text(
            GradleBuildFiles._app_build_gradle_content(
                package_name=package_name,
                archs=archs,
                compile_sdk=compile_sdk,
                min_sdk=min_sdk,
                target_sdk=target_sdk,
                python_version=python_version,
            )
        )
        (app_dir / "libs").mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _app_build_gradle_content(
        package_name: str,
        archs: list[Arch],
        compile_sdk: int,
        min_sdk: int,
        target_sdk: int,
        python_version: str,
    ) -> str:
        abi_filters = ", ".join(f'"{a.value}"' for a in archs)
        arch_list_kts = ", ".join(f'"{a.value}"' for a in archs)
        return f"""\
plugins {{
    id("com.android.application")
}}

android {{
    namespace = "{package_name}"
    compileSdk = {compile_sdk}

    defaultConfig {{
        applicationId = "{package_name}"
        minSdk = {min_sdk}
        targetSdk = {target_sdk}
        versionCode = 1
        versionName = "1.0"

        ndk {{
            abiFilters += setOf({abi_filters})
        }}
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }}
}}

dependencies {{
    implementation(fileTree("libs") {{ include("*.aar", "*.jar") }})
}}

{GradleBuildFiles._site_packages_tasks(arch_list_kts, python_version)}
"""

    @staticmethod
    def _site_packages_tasks(arch_list_kts: str, python_version: str) -> str:
        return f"""\
// ── site-packages copy tasks ─────────────────────────────────────────────────
val sitePackagesAbis = listOf({arch_list_kts})

tasks.register<Copy>("copySitePackagesToAssets") {{
    group = "python"
    description = "Sync site-packages into assets before each build (excludes .libs, .java, .kotlin)"
    val srcDir = sitePackagesAbis.map {{ file("../site_packages/$it") }}.firstOrNull {{ it.exists() }}
    if (srcDir != null) {{
        from(srcDir) {{
            exclude(".libs/**")
            exclude(".java/**")
            exclude(".kotlin/**")
        }}
        into("src/main/assets/python{python_version}/site-packages")
    }}
}}

tasks.register<Copy>("copySitePackagesJava") {{
    group = "python"
    description = "Copy .java sources from site-packages into the app java source set (first available arch)"
    val srcDir = sitePackagesAbis.map {{ file("../site_packages/$it/.java") }}.firstOrNull {{ it.exists() }}
    if (srcDir != null) {{
        from(srcDir)
        into("src/main/java")
    }}
}}

tasks.register<Copy>("copySitePackagesKotlin") {{
    group = "python"
    description = "Copy .kotlin sources from site-packages into the app kotlin source set (first available arch)"
    val srcDir = sitePackagesAbis.map {{ file("../site_packages/$it/.kotlin") }}.firstOrNull {{ it.exists() }}
    if (srcDir != null) {{
        from(srcDir)
        into("src/main/kotlin")
    }}
}}

tasks.named("preBuild") {{
    dependsOn("copySitePackagesToAssets")
    dependsOn("copySitePackagesJava")
    dependsOn("copySitePackagesKotlin")
}}
// ─────────────────────────────────────────────────────────────────────────────"""

    # -------------------------------------------------------------------------
    # AndroidManifest
    # -------------------------------------------------------------------------

    @staticmethod
    def write_android_manifest(
        main_dir: Path,
        package_name: str,
        app_name: str,
    ) -> None:
        content = f"""\
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:label="{app_name}"
        android:allowBackup="true"
        android:supportsRtl="true"
        android:hardwareAccelerated="true">

        <activity
            android:name=".MainActivity"
            android:label="{app_name}"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""
        (main_dir / "AndroidManifest.xml").write_text(content)
