"""Writes Gradle project files (Kotlin DSL / .kts). Ported from GradleBuildFiles.swift.

Swift-specific tasks (SwiftPM build / copy / Swift activity) are intentionally
omitted — generated projects are pure AGP."""

from __future__ import annotations

import shutil
import urllib.request
from pathlib import Path

from ..pyproject_toml import KivySchoolData
from .android_toolchain import DEFAULT_API_VERSION

Arch = KivySchoolData.AndroidData.Arch

_GRADLE_VERSION = "9.5.0"
# Gradle commits the wrapper jar to their own repo; download it directly so
# ksproject never needs a system-installed `gradle`.
_GRADLE_WRAPPER_JAR_URL = (
    "https://raw.githubusercontent.com/gradle/gradle"
    f"/refs/tags/v{_GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar"
)


class GradleBuildError(Exception):
    pass


class GradleBuildFiles:

    # -------------------------------------------------------------------------
    # Root project files
    # -------------------------------------------------------------------------

    @staticmethod
    def write_root_build_gradle(dir: Path) -> None:
        content = """\
// Top-level build file - generated by ksproject
plugins {
    id("com.android.application") version "8.9.1" apply false
    id("com.android.library") version "8.9.1" apply false
}
"""
        (dir / "build.gradle.kts").write_text(content, encoding="utf-8")

    @staticmethod
    def write_settings_gradle(dir: Path, app_name: str) -> None:
        content = f"""\
pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
        google()
        mavenCentral()
    }}
}}

rootProject.name = "{app_name}"
include(":app")
"""
        (dir / "settings.gradle.kts").write_text(content, encoding="utf-8")

    @staticmethod
    def write_gradle_properties(dir: Path) -> None:
        content = (
            "# Project-wide Gradle settings - generated by ksproject\n"
            "org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8\n"
            "org.gradle.configuration-cache=true\n"
            "android.useAndroidX=true\n"
            "android.nonTransitiveRClass=true\n"
        )
        (dir / "gradle.properties").write_text(content, encoding="utf-8")

    @staticmethod
    def write_local_properties(dir: Path, sdk_path: str) -> None:
        sdk_path = str(sdk_path).replace("\\", "/")
        (dir / "local.properties").write_text(f"sdk.dir={sdk_path}\n", encoding="utf-8")

    # -------------------------------------------------------------------------
    # Gradle wrapper
    # -------------------------------------------------------------------------

    @staticmethod
    def write_gradle_wrapper(dir: Path, java_path: str) -> None:
        wrapper_dir = dir / "gradle" / "wrapper"
        wrapper_dir.mkdir(parents=True, exist_ok=True)

        properties = (
            "distributionBase=GRADLE_USER_HOME\n"
            "distributionPath=wrapper/dists\n"
            f"distributionUrl=https\\://services.gradle.org/distributions/gradle-{_GRADLE_VERSION}-bin.zip\n"
            "networkTimeout=10000\n"
            "validateDistributionUrl=true\n"
            "zipStoreBase=GRADLE_USER_HOME\n"
            "zipStorePath=wrapper/dists\n"
        )
        (wrapper_dir / "gradle-wrapper.properties").write_text(
            properties, encoding="utf-8"
        )

        jar_path = wrapper_dir / "gradle-wrapper.jar"
        gradlew_path = dir / "gradlew"
        if jar_path.exists() and gradlew_path.exists():
            return

        _gh = f"https://raw.githubusercontent.com/gradle/gradle/refs/tags/v{_GRADLE_VERSION}"
        print(f"[ksproject] Downloading Gradle {_GRADLE_VERSION} wrapper files...")
        urllib.request.urlretrieve(_GRADLE_WRAPPER_JAR_URL, jar_path)
        urllib.request.urlretrieve(f"{_gh}/gradlew", gradlew_path)
        gradlew_path.chmod(0o755)
        urllib.request.urlretrieve(f"{_gh}/gradlew.bat", dir / "gradlew.bat")

    # -------------------------------------------------------------------------
    # App module
    # -------------------------------------------------------------------------

    @staticmethod
    def write_app_build_gradle(
        app_dir: Path,
        package_name: str,
        archs: list[Arch],
        compile_sdk: int = DEFAULT_API_VERSION,
        min_sdk: int = 24,
        target_sdk: int = DEFAULT_API_VERSION,
        python_version: str = "3.13",
        ndk_version: str | None = None,
        ndk_path: str | None | Path = None,
        aar: bool = False,
        gradle_dependencies: list[str] | None = None,
    ) -> None:
        (app_dir / "build.gradle.kts").write_text(
            GradleBuildFiles._app_build_gradle_content(
                package_name=package_name,
                archs=archs,
                compile_sdk=compile_sdk,
                min_sdk=min_sdk,
                target_sdk=target_sdk,
                python_version=python_version,
                ndk_version=ndk_version,
                ndk_path=ndk_path,
                aar=aar,
                gradle_dependencies=gradle_dependencies or [],
            ),
            encoding="utf-8",
        )
        (app_dir / "libs").mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _app_build_gradle_content(
        package_name: str,
        archs: list[Arch],
        compile_sdk: int,
        min_sdk: int,
        target_sdk: int,
        python_version: str,
        ndk_version: str | None = None,
        ndk_path: str | None | Path = None,
        aar: bool = False,
        gradle_dependencies: list[str] | None = None,
    ) -> str:
        abi_filters = ", ".join(f'"{a.value}"' for a in archs)
        arch_list_kts = ", ".join(f'"{a.value}"' for a in archs)
        ndk_line = f'    ndkVersion = "{ndk_version}"\n' if ndk_version else ""
        plugin_id = "com.android.library" if aar else "com.android.application"
        app_id_lines = (
            ""
            if aar
            else f'        applicationId = "{package_name}"\n'
            f"        versionCode = 1\n"
            f'        versionName = "1.0"\n'
        )
        extra_deps = "".join(
            f'    implementation("{dep}")\n' for dep in (gradle_dependencies or [])
        )
        ndk_path = str(ndk_path).replace("\\", "/") if ndk_path else ndk_path
        return f"""\
plugins {{
    id("{plugin_id}")
}}

android {{
    namespace = "{package_name}"
    compileSdk = {compile_sdk}
{ndk_line}
    ndkPath = "{ndk_path}"

    defaultConfig {{
{app_id_lines}        minSdk = {min_sdk}
        targetSdk = {target_sdk}

        ndk {{
            abiFilters += setOf({abi_filters})
        }}

        externalNativeBuild {{
            cmake {{
                arguments += listOf("-DANDROID_STL=c++_static")
            }}
        }}
    }}

    externalNativeBuild {{
        cmake {{
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }}
    }}

    buildTypes {{
        release {{
            isMinifyEnabled = false
        }}
    }}

    compileOptions {{
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }}

    // CPython stdlib and packages contain underscore-prefixed directories
    // (e.g. zipfile/_path) that AGP's default aapt ignore pattern strips.
    // Override to keep them.
    androidResources {{
        ignoreAssetsPatterns.clear()
        ignoreAssetsPatterns.addAll(listOf(
            "!.svn", "!.git", "!.ds_store", "!*.scc",
            "!CVS", "!thumbs.db", "!picasa.ini", "!*~"
        ))
    }}
}}

dependencies {{
    implementation(fileTree("libs") {{ include("*.aar", "*.jar") }})
{extra_deps}}}

{GradleBuildFiles._site_packages_tasks(arch_list_kts, python_version)}
"""

    @staticmethod
    def _site_packages_tasks(arch_list_kts: str, python_version: str) -> str:
        return f"""\
// ── site-packages copy tasks ─────────────────────────────────────────────────
val sitePackagesAbis = listOf({arch_list_kts})

// Copy each ABI's site-packages into assets/python{python_version}/site-packages/<abi>/
// At runtime the app loads from the subdirectory matching its ABI.
val copySitePackagesTasks = sitePackagesAbis.map {{ abi ->
    tasks.register<Copy>("copySitePackages_${{abi}}") {{
        group = "python"
        description = "Copy site-packages for $abi into assets"
        val srcDir = file("../site_packages/$abi")
        onlyIf {{ srcDir.exists() }}
        from(srcDir) {{
            exclude(".libs/**")
            exclude(".java/**")
            exclude(".kotlin/**")
            exclude(".gradle/**")
        }}
        into("src/main/assets/site-packages/$abi")
    }}
}}

tasks.register<Copy>("copySitePackagesJava") {{
    group = "python"
    description = "Copy .java sources from site-packages into the app java source set (first available arch)"
    val srcDir = sitePackagesAbis.map {{ file("../site_packages/$it/.java") }}.firstOrNull {{ it.exists() }}
    if (srcDir != null) {{
        from(srcDir)
        into("src/main/java")
    }}
}}

tasks.register<Copy>("copySitePackagesKotlin") {{
    group = "python"
    description = "Copy .kotlin sources from site-packages into the app kotlin source set (first available arch)"
    val srcDir = sitePackagesAbis.map {{ file("../site_packages/$it/.kotlin") }}.firstOrNull {{ it.exists() }}
    if (srcDir != null) {{
        from(srcDir)
        into("src/main/kotlin")
    }}
}}

// Copy .libs/<abi>/ → src/main/jniLibs/<abi>/ (libSDL2.so etc. ship inside the wheel)
val copySitePackagesNativeLibsTasks = sitePackagesAbis.map {{ abi ->
    tasks.register<Copy>("copySitePackagesNativeLibs_${{abi}}") {{
        group = "python"
        description = "Copy .libs/$abi native libraries into jniLibs/$abi"
        val srcDir = file("../site_packages/$abi/.libs/$abi")
        onlyIf {{ srcDir.exists() }}
        from(srcDir) {{
            include("*.so")
        }}
        into("src/main/jniLibs/$abi")
    }}
}}

tasks.named("preBuild") {{
    copySitePackagesTasks.forEach {{ dependsOn(it) }}
    copySitePackagesNativeLibsTasks.forEach {{ dependsOn(it) }}
    dependsOn("copySitePackagesJava")
    dependsOn("copySitePackagesKotlin")
}}
// ─────────────────────────────────────────────────────────────────────────────"""

    # -------------------------------------------------------------------------
    # AndroidManifest
    # -------------------------------------------------------------------------

    @staticmethod
    def write_android_manifest(
        main_dir: Path,
        package_name: str,
        project_dir: Path,
        app_name: str,
        permissions: list[str] | None = None,
        meta_data: dict[str, str] | None = None,
        services: list["KivySchoolData.ServiceData"] | None = None,
    ) -> None:

        perm_lines = "\n".join(
            f'    <uses-permission android:name="android.permission.{p}" />'
            for p in (permissions or ["INTERNET"])
        )

        meta_lines = "".join(
            f'\n        <meta-data android:name="{k}" android:value="{v}" />'
            for k, v in (meta_data or {}).items()
        )

        service_lines = ""
        if services:
            for svc in services:
                fg_type = (
                    f'\n            android:foregroundServiceType="{svc.foreground_service_type}"'
                    if svc.foreground_service_type
                    else ""
                )
                service_lines += f"""
        <service
            android:name=".{svc.name}"
            android:exported="false"
            android:process=":{svc.name.lower()}"{fg_type}>
        </service>"""

        template_path = project_dir / "AndroidManifest.tmpl.xml"

        if not template_path.exists():
            print(
                "AndroidManifest.tmpl.xml not found... Continuing with default template..."
            )
            default_template = """\
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

{{ permissions }}

    <application
        android:label="{{ app_name }}"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="true"
        android:supportsRtl="true"
        android:hardwareAccelerated="true"
        android:theme="@android:style/Theme.DeviceDefault.NoActionBar">{{ meta_data }}
{{ services }}
        <activity
            android:name=".MainActivity"
            android:label="{{ app_name }}"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:theme="@android:style/Theme.DeviceDefault.NoActionBar"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""
            template_path.write_text(default_template, encoding="utf-8")

        template_content = template_path.read_text(encoding="utf-8")

        manifest_content = template_content.replace("{{ app_name }}", app_name)
        manifest_content = manifest_content.replace("{{ permissions }}", perm_lines)
        manifest_content = manifest_content.replace("{{ meta_data }}", meta_lines)
        manifest_content = manifest_content.replace("{{ services }}", service_lines)

        (main_dir / "AndroidManifest.xml").write_text(
            manifest_content, encoding="utf-8"
        )

    # -------------------------------------------------------------------------
    # Icon
    # -------------------------------------------------------------------------

    @staticmethod
    def write_icon(res_dir: Path, icon_src: Path) -> None:
        mipmap_dir = res_dir / "mipmap"
        mipmap_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(icon_src, mipmap_dir / "ic_launcher.png")

    # -------------------------------------------------------------------------
    # MainActivity.java — extends PythonActivity (SDL2 AAR provides the class)
    # -------------------------------------------------------------------------

    @staticmethod
    def write_main_activity(
        main_dir: Path,
        package_name: str,
        python_version: str,
        python_module: str,
        presplash_type: str | None = None,
        presplash_name: str | None = None,
        presplash_color: str = "#FFFFFF",
    ) -> None:
        java_dir = main_dir / "java" / Path(*package_name.split("."))
        java_dir.mkdir(parents=True, exist_ok=True)

        show_presplash_code = ""
        if presplash_type and presplash_name:
            show_presplash_code = f'showLoadingScreen("{presplash_type}", "{presplash_name}", "{presplash_color}");'

        content = f"""\
package {package_name};

import android.content.res.AssetManager;
import android.os.Build;
import android.os.Bundle;
import android.system.ErrnoException;
import android.system.Os;
import android.util.Log;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import org.kivy.android.PythonActivity;

public class MainActivity extends PythonActivity {{
    private static final String TAG = "ksproject";

    @Override
    protected String[] getLibraries() {{
        return new String[] {{
            "SDL2",
            "python3",
            "main",
        }};
    }}

    @Override
    protected void onCreate(Bundle savedInstanceState) {{
        mActivity = this;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {{
            mActivity.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            mActivity.getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);
            mActivity.getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
            mActivity.getWindow().setStatusBarColor(android.graphics.Color.TRANSPARENT);
            mActivity.getWindow().setNavigationBarColor(android.graphics.Color.TRANSPARENT);

            mActivity.getWindow().getDecorView().setSystemUiVisibility(
                android.view.View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | android.view.View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | android.view.View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            );
        }}

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {{
            mActivity.getWindow().setNavigationBarContrastEnforced(false);
            mActivity.getWindow().setStatusBarContrastEnforced(false);
        }}

        final File appDir = new File(getFilesDir(), "app");
        String appPath = appDir.getAbsolutePath();
        String privatePath = getFilesDir().getAbsolutePath();

        setEnv("ANDROID_APP_PATH", appPath);
        setEnv("ANDROID_ARGUMENT", appPath);
        setEnv("ANDROID_PRIVATE", privatePath);
        setEnv("ANDROID_UNPACK", appPath);
        setEnv("ANDROID_ENTRYPOINT", "{str(python_module).strip().replace('-', '_').replace('.', '_').replace(' ', '_')}");
        setEnv("ANDROID_NATIVE_LIB_DIR", getApplicationInfo().nativeLibraryDir);
        setEnv("PYTHONHOME", appPath);
        setEnv("PYTHONNOUSERSITE", "1");
        setEnv("PYTHONUNBUFFERED", "1");
        setEnv("P4A_BOOTSTRAP", "SDL2");
        setEnv("APP_ACTIVITY", "{package_name}.MainActivity");
        setEnv("PYTHONOPTIMIZE", "2");

        super.onCreate(savedInstanceState);

        {show_presplash_code}

        final File unpackDoneFile = new File(appDir, ".unpack_done");
        if (!unpackDoneFile.exists()) {{
            new Thread(new Runnable() {{
                @Override
                public void run() {{
                    if (!appDir.exists()) appDir.mkdirs();
                    try {{
                        unpackAsset(getAssets(), "python{python_version}", appDir);
                        String abi = pickAbi(getAssets(), "site-packages");
                        if (abi != null) {{
                            File sitePackages = new File(appDir, "site-packages");
                            sitePackages.mkdirs();
                            unpackAssetTree(getAssets(), "site-packages/" + abi, sitePackages);
                        }} else {{
                            Log.e(TAG, "no matching ABI found in assets/site-packages");
                        }}
                        String dynAbi = pickAbi(getAssets(), "lib-dynload");
                        if (dynAbi != null) {{
                            File dynload = new File(appDir, "python{python_version}/lib-dynload");
                            dynload.mkdirs();
                            unpackAssetTree(getAssets(), "lib-dynload/" + dynAbi, dynload);
                        }}
                        
                        // Signal to main.c that extraction is complete
                        unpackDoneFile.createNewFile();
                    }} catch (IOException e) {{
                        Log.e(TAG, "asset unpack failed", e);
                    }}
                }}
            }}).start();
        }}
    }}

    private static String pickAbi(AssetManager am, String root)
            throws IOException {{
        String[] available = am.list(root);
        if (available == null) return null;
        for (String supported : Build.SUPPORTED_ABIS) {{
            for (String entry : available) {{
                if (entry.equals(supported)) return supported;
            }}
        }}
        return null;
    }}

    private static void setEnv(String name, String value) {{
        try {{
            Os.setenv(name, value, true);
        }} catch (ErrnoException e) {{
            Log.e(TAG, "setenv " + name + " failed", e);
        }}
    }}

    private static void unpackAsset(AssetManager am, String src, File destRoot)
            throws IOException {{
        String[] entries = am.list(src);
        File outFile = new File(destRoot, src);

        if (entries == null || entries.length == 0) {{
            // It's a file - Unpack it
            File parent = outFile.getParentFile();
            if (parent != null && !parent.exists()) {{
                parent.mkdirs();
            }}

            // Using Buffered streams and a larger 16KB buffer for faster I/O
            try (InputStream in = new java.io.BufferedInputStream(am.open(src));
                 OutputStream out = new java.io.BufferedOutputStream(new FileOutputStream(outFile))) {{
                byte[] buf = new byte[16384]; 
                int n;
                while ((n = in.read(buf)) > 0) {{
                    out.write(buf, 0, n);
                }}
            }}
        }} else {{
            // It's a directory - Recurse
            if (!outFile.exists()) {{
                outFile.mkdirs();
            }}
            for (String child : entries) {{
                // Template will process the string concatenation here
                unpackAsset(am, src + "/" + child, destRoot);
            }}
        }}
    }}

    /** Like unpackAsset but strips the leading {{srcRoot}} so that
     * assets/site-packages/x86_64/foo lands as destRoot/foo. */
    private static void unpackAssetTree(
        AssetManager am, String srcRoot, File destRoot
    ) throws IOException {{
        unpackAssetTreeRec(am, srcRoot, srcRoot, destRoot);
    }}

    private static void unpackAssetTreeRec(
        AssetManager am, String srcRoot, String current, File destRoot
    ) throws IOException {{
        String[] entries = am.list(current);
        if (entries == null || entries.length == 0) {{
            // It's a file - calculate relative path and unpack it
            String rel = current.length() > srcRoot.length()
                ? current.substring(srcRoot.length() + 1)
                : "";
            File outFile = new File(destRoot, rel);
            
            File parent = outFile.getParentFile();
            if (parent != null && !parent.exists()) {{
                parent.mkdirs();
            }}

            try (InputStream in = new java.io.BufferedInputStream(am.open(current));
                 OutputStream out = new java.io.BufferedOutputStream(new FileOutputStream(outFile))) {{
                byte[] buf = new byte[16384];
                int n;
                while ((n = in.read(buf)) > 0) {{
                    out.write(buf, 0, n);
                }}
            }}
            return;
        }}

        // It's a directory - loop through children and recurse
        for (String child : entries) {{
            unpackAssetTreeRec(am, srcRoot, current + "/" + child, destRoot);
        }}
    }}
}}
"""
        dest = java_dir / "MainActivity.java"
        dest.write_text(content, encoding="utf-8")

    # -------------------------------------------------------------------------
    # Hardware.java — org.renpy.android.Hardware shim for Kivy SDL2 metrics
    # -------------------------------------------------------------------------

    @staticmethod
    def write_renpy_hardware(main_dir: Path, package_name: str) -> None:
        """Minimal org.renpy.android.Hardware that Kivy 2.3 (SDL2) calls into
        for DPI / display metrics. Delegates to MainActivity.mActivity."""
        java_dir = main_dir / "java" / "org" / "renpy" / "android"
        java_dir.mkdir(parents=True, exist_ok=True)
        content = f"""\
package org.renpy.android;

import android.util.DisplayMetrics;
import {package_name}.MainActivity;

public class Hardware {{
    public static DisplayMetrics metrics = new DisplayMetrics();

    public static int getDPI() {{
        MainActivity.mActivity.getWindowManager()
            .getDefaultDisplay().getMetrics(metrics);
        return metrics.densityDpi;
    }}
}}
"""
        (java_dir / "Hardware.java").write_text(content, encoding="utf-8")

    # -------------------------------------------------------------------------
    # PythonActivity.java — org.kivy.android.PythonActivity shim
    # -------------------------------------------------------------------------

    @staticmethod
    def write_kivy_python_activity(main_dir: Path, package_name: str) -> None:
        """Minimal org.kivy.android.PythonActivity that exposes mActivity to
        Kivy's fontscale lookup via pyjnius, combining native p4a lifecycle safety
        with dynamic Lottie/GIF/Image loading screens."""
        java_dir = main_dir / "java" / "org" / "kivy" / "android"
        java_dir.mkdir(parents=True, exist_ok=True)

        content = f"""\
package org.kivy.android;

import android.app.Activity;
import org.libsdl.app.SDLActivity;
import android.content.pm.PackageManager;
import android.util.Log;
import android.content.Context;
import android.view.inputmethod.InputMethodManager;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;

public class PythonActivity extends SDLActivity {{
    public static PythonActivity mActivity;
    public static final String TAG = "PythonActivity";
    
    private View loadingView = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {{
        super.onCreate(savedInstanceState);
        mActivity = this;
    }}

    public static PythonActivity getActivity() {{
        return mActivity;
    }}

    protected void showLoadingScreen(View view) {{
        try {{
            if (mLayout == null) {{
                setContentView(view);
            }} else if (view.getParent() == null) {{
                mLayout.addView(view);
            }}
        }} catch (IllegalStateException e) {{
            // The loading screen can be attempted to be applied twice if app
            // is tabbed in/out, quickly.
            // (Gives error "The specified child already has a parent.
            // You must call removeView() on the child's parent first.")
            Log.w(TAG, "Loading screen attempted to be applied twice.");
        }}
    }}

    /**
     * Show custom loading screen overlay using the safe p4a application method.
     * @param type "lottie", "gif", or "image"
     * @param resourceName filename without extension (e.g. "loading_anim")
     * @param bgColor Hex color string for background (e.g. "#FFFFFF")
     */
    public void showLoadingScreen(final String type, final String resourceName, final String bgColor) {{
        runOnUiThread(new Runnable() {{
            @Override
            public void run() {{
                // If the view already exists (e.g., resuming app), just re-apply it safely
                if (loadingView != null) {{
                    showLoadingScreen(loadingView);
                    return;
                }}

                FrameLayout frameLayout = new FrameLayout(mActivity);
                
                // Force the background layout to fill the entire screen
                frameLayout.setLayoutParams(new ViewGroup.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                ));

                try {{
                    frameLayout.setBackgroundColor(Color.parseColor(bgColor));
                }} catch (Exception e) {{
                    frameLayout.setBackgroundColor(Color.WHITE);
                }}

                FrameLayout.LayoutParams centerParams = new FrameLayout.LayoutParams(
                        FrameLayout.LayoutParams.WRAP_CONTENT,
                        FrameLayout.LayoutParams.WRAP_CONTENT,
                        android.view.Gravity.CENTER
                );

                int resId = getResources().getIdentifier(resourceName, "drawable", getPackageName());
                int rawResId = getResources().getIdentifier(resourceName, "raw", getPackageName());

                try {{
                    if ("lottie".equalsIgnoreCase(type)) {{
                        try {{
                            Class<?> lottieClass = Class.forName("com.airbnb.lottie.LottieAnimationView");
                            View lottieView = (View) lottieClass.getConstructor(Context.class).newInstance(mActivity);
                            
                            if (rawResId != 0) {{
                                lottieClass.getMethod("setAnimation", int.class).invoke(lottieView, rawResId);
                            }} else {{
                                lottieClass.getMethod("setAnimation", String.class).invoke(lottieView, resourceName + ".json");
                            }}
                            
                            lottieClass.getMethod("setRepeatCount", int.class).invoke(lottieView, -1);
                            lottieClass.getMethod("playAnimation").invoke(lottieView);
                            frameLayout.addView(lottieView, centerParams);
                        }} catch (ClassNotFoundException e) {{
                            Log.e(TAG, "Lottie class not found. Ensure it is in your gradle dependencies.");
                        }}
                        
                    }} else if ("gif".equalsIgnoreCase(type)) {{
                        ImageView imageView = new ImageView(mActivity);
                        if (Build.VERSION.SDK_INT >= 28 && resId != 0) {{
                            android.graphics.ImageDecoder.Source source = android.graphics.ImageDecoder.createSource(getResources(), resId);
                            android.graphics.drawable.Drawable drawable = android.graphics.ImageDecoder.decodeDrawable(source);
                            imageView.setImageDrawable(drawable);
                            if (drawable instanceof android.graphics.drawable.AnimatedImageDrawable) {{
                                ((android.graphics.drawable.AnimatedImageDrawable) drawable).start();
                            }}
                        }} else {{
                            if (resId != 0) imageView.setImageResource(resId);
                        }}
                        frameLayout.addView(imageView, centerParams);
                        
                    }} else {{
                        ImageView imageView = new ImageView(mActivity);
                        if (resId != 0) imageView.setImageResource(resId);
                        frameLayout.addView(imageView, centerParams);
                    }}

                    loadingView = frameLayout;
                    
                    // Route the newly constructed View through the safe p4a method
                    showLoadingScreen(loadingView);
                    Log.v(TAG, "Loading screen constructed and displayed: " + type);

                }} catch (Exception e) {{
                    Log.e(TAG, "Error creating loading screen: " + e.getMessage());
                }}
            }}
        }});
    }}

    public void removeLoadingScreen() {{
        runOnUiThread(new Runnable() {{
            @Override
            public void run() {{
                if (loadingView != null && loadingView.getParent() != null) {{
                    loadingView.animate()
                        .alpha(0f)
                        .setDuration(300)
                        .withEndAction(new Runnable() {{
                            @Override
                            public void run() {{
                                if (loadingView != null && loadingView.getParent() != null) {{
                                    ((ViewGroup) loadingView.getParent()).removeView(loadingView);
                                    loadingView = null;
                                    Log.v(TAG, "Loading screen successfully removed");
                                }}
                            }}
                        }})
                        .start();
                }}
            }}
        }});
    }}

    /**
     * Used by android.permissions module to register a call back after requesting runtime
     * permissions
     */
    public interface PermissionsCallback {{
        void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults);
    }}

    private PermissionsCallback permissionCallback;
    private boolean havePermissionsCallback = false;

    public void addPermissionsCallback(PermissionsCallback callback) {{
        permissionCallback = callback;
        havePermissionsCallback = true;
        Log.v(TAG, "addPermissionsCallback(): Added callback for onRequestPermissionsResult");
    }}

    @Override
    public void onRequestPermissionsResult(
            int requestCode, String[] permissions, int[] grantResults) {{
        Log.v(TAG, "onRequestPermissionsResult()");
        if (havePermissionsCallback) {{
            Log.v(TAG, "onRequestPermissionsResult passed to callback");
            permissionCallback.onRequestPermissionsResult(requestCode, permissions, grantResults);
        }}
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }}

    /** Used by android.permissions module to check a permission */
    public boolean checkCurrentPermission(String permission) {{
        return checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED;
    }}

    /** Used by android.permissions module to request runtime permissions */
    public void requestPermissionsWithRequestCode(String[] permissions, int requestCode) {{
        requestPermissions(permissions, requestCode);
    }}

    public void requestPermissions(String[] permissions) {{
        requestPermissionsWithRequestCode(permissions, 1);
    }}

    public static void changeKeyboard(int inputType) {{
        // empty
    }}
}}
"""
        (java_dir / "PythonActivity.java").write_text(content, encoding="utf-8")

    @staticmethod
    def write_kivy_python_service(main_dir: Path) -> None:
        """Base PythonService matching p4a architecture with critical SDL/Pyjnius hooks."""
        java_dir = main_dir / "java" / "org" / "kivy" / "android"
        java_dir.mkdir(parents=True, exist_ok=True)
        content = """\
package org.kivy.android;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.os.IBinder;
import android.os.Process;
import android.util.Log;
import android.system.Os;
import android.system.ErrnoException;
import java.io.File;
import java.lang.reflect.Method;
import java.lang.reflect.InvocationTargetException;
import org.libsdl.app.SDL;

public class PythonService extends Service implements Runnable {

    private Thread pythonThread = null;

    private String androidPrivate;
    private String serviceEntrypoint;
    private String pythonVersion;
    private String pythonName;

    public static PythonService mService = null;
    private Intent startIntent = null;
    private boolean autoRestartService = false;

    static {
        System.loadLibrary("SDL2");
        System.loadLibrary("python3");
        System.loadLibrary("service_main");
    }

    public void setAutoRestartService(boolean restart) {
        autoRestartService = restart;
    }

    public int startType() {
        return START_NOT_STICKY;
    }

    @Override
    public IBinder onBind(Intent arg0) {
        return null;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SDL.setContext(this);
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        if (pythonThread != null) {
            Log.v("python service", "service exists, do not start again");
            return startType();
        }
        if (intent == null) {
            Context context = getApplicationContext();
            intent = getThisDefaultIntent(context, "");
        }

        startIntent = intent;
        Bundle extras = intent.getExtras();
        if (extras != null) {
            androidPrivate = extras.getString("androidPrivate");
            serviceEntrypoint = extras.getString("serviceEntrypoint");
            pythonVersion = extras.getString("pythonVersion");
            pythonName = extras.getString("pythonName");
            
            boolean serviceStartAsForeground = false;
            if (extras.containsKey("serviceStartAsForeground")) {
                serviceStartAsForeground = extras.getString("serviceStartAsForeground").equals("true");
            }

            pythonThread = new Thread(this);
            pythonThread.start();

            if (serviceStartAsForeground) {
                doStartForeground(extras);
            }
        }

        return startType();
    }

    protected int getServiceId() {
        return 1;
    }

    protected Intent getThisDefaultIntent(Context ctx, String pythonServiceArgument) {
        return null;
    }

    protected void doStartForeground(Bundle extras) {
        String serviceTitle = extras.getString("serviceTitle");
        String smallIconName = extras.getString("smallIconName");
        String contentTitle = extras.getString("contentTitle");
        String contentText = extras.getString("contentText");
        Notification notification;
        Context context = getApplicationContext();
        Intent contextIntent = new Intent(context, PythonActivity.class);
        PendingIntent pIntent = PendingIntent.getActivity(
                context, 0, contextIntent,
                PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_UPDATE_CURRENT);

        int smallIconId = context.getApplicationInfo().icon;
        if (smallIconName != null && !smallIconName.equals("")) {
            int resId = getResources().getIdentifier(smallIconName, "mipmap", getPackageName());
            if (resId == 0) {
                resId = getResources().getIdentifier(smallIconName, "drawable", getPackageName());
            }
            if (resId != 0) {
                smallIconId = resId;
            }
        }

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            notification = new Notification(smallIconId, serviceTitle, System.currentTimeMillis());
            try {
                Method func = notification.getClass().getMethod(
                        "setLatestEventInfo", Context.class, CharSequence.class, CharSequence.class, PendingIntent.class);
                func.invoke(notification, context, contentTitle, contentText, pIntent);
            } catch (Exception e) {
                Log.e("python service", "Notification legacy setup failed", e);
            }
        } else {
            String NOTIFICATION_CHANNEL_ID = "org.kivy.p4a" + getServiceId();
            String channelName = "Background Service" + getServiceId();
            NotificationChannel chan = new NotificationChannel(
                    NOTIFICATION_CHANNEL_ID, channelName, NotificationManager.IMPORTANCE_NONE);

            chan.setLightColor(Color.BLUE);
            chan.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
            NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
            manager.createNotificationChannel(chan);

            Notification.Builder builder = new Notification.Builder(context, NOTIFICATION_CHANNEL_ID);
            builder.setContentTitle(contentTitle);
            builder.setContentText(contentText);
            builder.setContentIntent(pIntent);
            builder.setSmallIcon(smallIconId);
            notification = builder.build();
        }
        startForeground(getServiceId(), notification);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        pythonThread = null;
        if (autoRestartService && startIntent != null) {
            Log.v("python service", "service restart requested");
            startService(startIntent);
        }
        Process.killProcess(Process.myPid());
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        super.onTaskRemoved(rootIntent);
        if (startType() != START_STICKY) {
            stopSelf();
        }
    }

    @Override
    public void run() {

        SDL.setupJNI();

        try {
            Os.setenv("ANDROID_NATIVE_LIB_DIR", getApplicationInfo().nativeLibraryDir, true);
        } catch (ErrnoException e) {
            Log.e("python service", "setenv ANDROID_NATIVE_LIB_DIR failed", e);
        }

        this.mService = this;
        nativeStart(
                androidPrivate,
                serviceEntrypoint,
                pythonVersion);
        stopSelf();
    }

    public static native void nativeStart(
            String androidPrivate,
            String entrypoint,
            String pyVersion);
}
"""
        (java_dir / "PythonService.java").write_text(content, encoding="utf-8")

    @staticmethod
    def write_custom_service(
        main_dir: Path,
        package_name: str,
        service_name: str,
        python_version: str,
        entrypoint: str,
        foreground: bool,
        start_type: str = "START_NOT_STICKY",
        notification_title: str | None = "",
        notification_text: str | None = "",
        notification_icon: str = "stat_notify_sync",
    ) -> None:
        java_dir = main_dir / "java" / Path(*package_name.split("."))
        java_dir.mkdir(parents=True, exist_ok=True)

        foreground_imports = ""
        foreground_logic = ""

        start_type_constant = start_type.upper()
        is_sticky_bool_str = (
            "true" if start_type_constant == "START_STICKY" else "false"
        )

        title = notification_title or f"{service_name} is running"
        text = notification_text or "Background task active"

        if foreground:
            foreground_imports = """
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.os.Build;
import android.content.Context;
"""
            foreground_logic = f"""
        String channelId = "{package_name}.{service_name}";
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {{
            NotificationChannel channel = new NotificationChannel(
                channelId,
                "{service_name} Channel",
                NotificationManager.IMPORTANCE_LOW
            );
            NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
            if (manager != null) {{
                manager.createNotificationChannel(channel);
            }}
        }}

        int iconId = getResources().getIdentifier("{notification_icon}", "drawable", "android");
        if (iconId == 0) {{
            iconId = android.R.drawable.stat_notify_sync;
        }}

        // Prioritize dynamic Intent titles (if launched from Python), otherwise use our Python defaults
        String finalTitle = intent.hasExtra("serviceTitle") ? intent.getStringExtra("serviceTitle") : "{title}";
        String finalText = intent.hasExtra("serviceDescription") ? intent.getStringExtra("serviceDescription") : "{text}";

        Notification notification;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {{
            notification = new Notification.Builder(this, channelId)
                .setContentTitle(finalTitle)
                .setContentText(finalText)
                .setSmallIcon(iconId)
                .build();
        }} else {{
            notification = new Notification.Builder(this)
                .setContentTitle(finalTitle)
                .setContentText(finalText)
                .setSmallIcon(iconId)
                .build();
        }}

        startForeground(1, notification);

        intent.putExtra("serviceStartAsForeground", "false");
"""

        content = f"""\
package {package_name};

import android.content.Context;
import android.content.Intent;
import org.kivy.android.PythonService;
import java.io.File;{foreground_imports}

public class {service_name} extends PythonService {{
    
    @Override
    public int startType() {{
        return {start_type_constant};
    }}

    @Override
    protected Intent getThisDefaultIntent(Context ctx, String pythonServiceArgument) {{
        Intent intent = new Intent(ctx, {service_name}.class);
        intent.putExtra("androidPrivate", ctx.getFilesDir().getAbsolutePath());
        intent.putExtra("serviceEntrypoint", "{entrypoint}");
        intent.putExtra("pythonVersion", "{python_version}");
        intent.putExtra("pythonName", "{service_name.lower()}");
        
        // Set fallback titles for when the system auto-restarts the service
        intent.putExtra("serviceTitle", "{title}");
        intent.putExtra("serviceDescription", "{text}");
        intent.putExtra("serviceStartAsForeground", "{'true' if foreground else 'false'}");
        
        return intent;
    }}

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {{
        if (intent == null || intent.getExtras() == null || !intent.hasExtra("pythonName")) {{
            intent = getThisDefaultIntent(getApplicationContext(), "");
        }} else {{
            // Ensure title and description are present even if launched normally via Python without them
            if (!intent.hasExtra("serviceTitle")) {{
                intent.putExtra("serviceTitle", "{title}");
            }}
            if (!intent.hasExtra("serviceDescription")) {{
                intent.putExtra("serviceDescription", "{text}");
            }}
        }}
        {foreground_logic}
        setAutoRestartService({is_sticky_bool_str});
        
        return super.onStartCommand(intent, flags, startId);
    }}
}}
"""
        (java_dir / f"{service_name}.java").write_text(content, encoding="utf-8")

    # -------------------------------------------------------------------------
    # Native bootstrap — libmain.so (provides SDL_main → CPython)
    # -------------------------------------------------------------------------

    @staticmethod
    def write_main_c(cpp_dir: Path, python_version: str, project_name: str) -> None:
        cpp_dir.mkdir(parents=True, exist_ok=True)
        content = f"""\
/* ksproject native bootstrap: SDL_main -> CPython
 * SDL_main.h #defines main as SDL_main; SDLActivity's native thread calls
 * SDL_main after System.loadLibrary("main"). We initialize CPython, set
 * up module search paths against the unpacked assets, then run main.py.
 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <SDL.h>
#include <SDL_main.h>
#include <android/log.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <wchar.h>

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  "ksproject", __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "ksproject", __VA_ARGS__)

static PyObject *androidembed_log(PyObject *self, PyObject *args) {{
    const char *s;
    if (!PyArg_ParseTuple(args, "s", &s)) return NULL;
    __android_log_write(ANDROID_LOG_INFO, "python", s);
    Py_RETURN_NONE;
}}

static PyMethodDef AndroidEmbedMethods[] = {{
    {{"log", androidembed_log, METH_VARARGS, "log to android logcat"}},
    {{NULL, NULL, 0, NULL}}
}};

static struct PyModuleDef androidembed_mod = {{
    PyModuleDef_HEAD_INIT, "androidembed", NULL, -1, AndroidEmbedMethods
}};

PyMODINIT_FUNC PyInit_androidembed(void) {{
    return PyModule_Create(&androidembed_mod);
}}

static const char *REDIRECT_STDIO =
    "import sys, androidembed\\n"
    "class _LogFile:\\n"
    "    def __init__(self): self._buf = ''\\n"
    "    def write(self, s):\\n"
    "        self._buf += s\\n"
    "        while chr(10) in self._buf:\\n"
    "            i = self._buf.index(chr(10))\\n"
    "            androidembed.log(self._buf[:i])\\n"
    "            self._buf = self._buf[i+1:]\\n"
    "    def flush(self):\\n"
    "        if self._buf:\\n"
    "            androidembed.log(self._buf); self._buf = ''\\n"
    "sys.stdout = sys.stderr = _LogFile()\\n";

int main(int argc, char *argv[]) {{
    (void)argc; (void)argv;
    LOGI("SDL_main entered");

    const char *app_path = getenv("ANDROID_APP_PATH");
    const char *entrypoint = getenv("ANDROID_ENTRYPOINT");
    if (!app_path || !entrypoint) {{
        LOGE("missing ANDROID_APP_PATH / ANDROID_ENTRYPOINT");
        return 1;
    }}

    char done_path[1024];
    snprintf(done_path, sizeof(done_path), "%s/.unpack_done", app_path);
    while (access(done_path, F_OK) != 0) {{
        usleep(50000); // Sleep for 50ms while presplash is displaying on the UI thread
    }}
    
    /* Env vars untill we patch Kivy platform check*/
    setenv("KIVY_NO_FILELOG", "1", 1);
    setenv("KIVY_NO_CONFIG", "1", 1);
    setenv("KIVY_BUILD", "android", 1);
    if (app_path) {{
        setenv("KIVY_HOME", app_path, 1);
    }}

    if (chdir(app_path) != 0) {{
        LOGE("chdir(%s) failed", app_path);
    }}

    PyImport_AppendInittab("androidembed", PyInit_androidembed);

    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);
    config.parse_argv = 0;
    config.install_signal_handlers = 0;
    config.write_bytecode = 0;
    config.use_environment = 1;

    wchar_t w_stdlib[1024];
    wchar_t w_dynload[1024];
    wchar_t w_site[1024];
    wchar_t w_project_site[1024];
    wchar_t w_app[1024];
    swprintf(w_stdlib,  1024, L"%s/python{python_version}", app_path);
    swprintf(w_dynload, 1024, L"%s/python{python_version}/lib-dynload", app_path);
    swprintf(w_site,    1024, L"%s/site-packages", app_path);
    swprintf(w_project_site, 1024, L"%s/site-packages/{project_name}", app_path);
    swprintf(w_app,     1024, L"%s", app_path);
    config.module_search_paths_set = 1;
    PyWideStringList_Append(&config.module_search_paths, w_stdlib);
    PyWideStringList_Append(&config.module_search_paths, w_dynload);
    PyWideStringList_Append(&config.module_search_paths, w_site);
    PyWideStringList_Append(&config.module_search_paths, w_project_site);
    PyWideStringList_Append(&config.module_search_paths, w_app);
    const char *native_lib_dir = getenv("ANDROID_NATIVE_LIB_DIR");
    if (native_lib_dir) {{
        wchar_t w_native[1024];
        swprintf(w_native, 1024, L"%s", native_lib_dir);
        PyWideStringList_Append(&config.module_search_paths, w_native);
    }}

    PyStatus status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) {{
        LOGE("Py_InitializeFromConfig failed: %s",
             status.err_msg ? status.err_msg : "(no message)");
        return 1;
    }}
    LOGI("Python initialized");

    PyRun_SimpleString(REDIRECT_STDIO);
    
    /* Run `python -m <entrypoint>` via runpy. The entrypoint env var is the
     * importable package or module name, not a filesystem path. */
    PyObject *runpy = PyImport_ImportModule("runpy");
    if (!runpy) {{
        LOGE("import runpy failed");
        if (PyErr_Occurred()) PyErr_Print();
        Py_FinalizeEx();
        return 1;
    }}
    PyObject *func = PyObject_GetAttrString(runpy, "run_module");
    if (!func) {{
        LOGE("runpy has no run_module");
        Py_DECREF(runpy);
        Py_FinalizeEx();
        return 1;
    }}
    PyObject *args_tuple = PyTuple_Pack(1, PyUnicode_FromString(entrypoint));
    PyObject *kwargs = Py_BuildValue("{{s:s, s:i}}",
                                     "run_name", "__main__",
                                     "alter_sys", 1);
    LOGI("running module: %s", entrypoint);
    PyObject *result = PyObject_Call(func, args_tuple, kwargs);
    Py_DECREF(args_tuple);
    Py_DECREF(kwargs);
    Py_DECREF(func);
    Py_DECREF(runpy);

    int ret = 0;
    if (!result) {{
        LOGE("python entrypoint raised");
        PyErr_Print();
        ret = 1;
    }} else {{
        Py_DECREF(result);
    }}

    Py_FinalizeEx();
    LOGI("python exit %d", ret);
    exit(ret);
    return ret;
}}
"""
        (cpp_dir / "main.c").write_text(content, encoding="utf-8")

    @staticmethod
    def write_service_main_c(cpp_dir: Path, project_name: str) -> None:
        cpp_dir.mkdir(parents=True, exist_ok=True)
        content = """\
#define PY_SSIZE_T_CLEAN
#include <jni.h>
#include <Python.h>
#include <android/log.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  "ksproject-service", __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "ksproject-service", __VA_ARGS__)

// Include the same AndroidEmbed implementation as main.c
static PyObject *androidembed_log(PyObject *self, PyObject *args) {
    const char *s;
    if (!PyArg_ParseTuple(args, "s", &s)) return NULL;
    __android_log_write(ANDROID_LOG_INFO, "python-service", s);
    Py_RETURN_NONE;
}

static PyMethodDef AndroidEmbedMethods[] = {
    {"log", androidembed_log, METH_VARARGS, "log to android logcat"},
    {NULL, NULL, 0, NULL}
};

static struct PyModuleDef androidembed_mod = {
    PyModuleDef_HEAD_INIT, "androidembed", NULL, -1, AndroidEmbedMethods
};

PyMODINIT_FUNC PyInit_androidembed(void) {
    return PyModule_Create(&androidembed_mod);
}

static const char *REDIRECT_STDIO =
    "import sys, androidembed\\n"
    "class _LogFile:\\n"
    "    def __init__(self): self._buf = ''\\n"
    "    def write(self, s):\\n"
    "        self._buf += s\\n"
    "        while chr(10) in self._buf:\\n"
    "            i = self._buf.index(chr(10))\\n"
    "            androidembed.log(self._buf[:i])\\n"
    "            self._buf = self._buf[i+1:]\\n"
    "    def flush(self):\\n"
    "        if self._buf:\\n"
    "            androidembed.log(self._buf); self._buf = ''\\n"
    "sys.stdout = sys.stderr = _LogFile()\\n";

JNIEXPORT jint JNICALL
Java_org_kivy_android_PythonService_nativeStart(
    JNIEnv *env, jobject thiz, jstring j_androidPrivate, jstring j_entrypoint, jstring j_pyVersion) {

    const char *private_path = (*env)->GetStringUTFChars(env, j_androidPrivate, NULL);
    const char *entrypoint = (*env)->GetStringUTFChars(env, j_entrypoint, NULL);
    const char *py_version = (*env)->GetStringUTFChars(env, j_pyVersion, NULL);

    char app_path[1024];
    snprintf(app_path, sizeof(app_path), "%s/app", private_path);

    LOGI("Service starting. App Path: %s, Entry: %s", app_path, entrypoint);

    char done_path[1024];
    snprintf(done_path, sizeof(done_path), "%s/.unpack_done", app_path);
    while (access(done_path, F_OK) != 0) {
        usleep(50000); // Sleep for 50ms while presplash is displaying on the UI thread
    }

    if (chdir(app_path) != 0) {
        LOGE("chdir(%s) failed", app_path);
    }

    setenv("ANDROID_APP_PATH", app_path, 1);
    setenv("ANDROID_ENTRYPOINT", entrypoint, 1);
    setenv("ANDROID_ARGUMENT", app_path, 1);
    setenv("ANDROID_PRIVATE", private_path, 1);
    setenv("ANDROID_UNPACK", app_path, 1);

    setenv("PYTHONHOME", app_path, 1);
    setenv("PYTHONNOUSERSITE", "1", 1);
    setenv("PYTHONUNBUFFERED", "1", 1);
    setenv("PYTHONOPTIMIZE", "2", 1);

    // just to make sure no abnormalities
    setenv("KIVY_NO_FILELOG", "1", 1);
    setenv("KIVY_NO_CONFIG", "1", 1);
    setenv("KIVY_BUILD", "android", 1);
    setenv("KIVY_HOME", app_path, 1);

    PyImport_AppendInittab("androidembed", PyInit_androidembed);

    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);
    config.parse_argv = 0;
    config.install_signal_handlers = 0;
    config.write_bytecode = 0;
    config.use_environment = 1;

    // Build paths
    wchar_t w_stdlib[1024], w_dynload[1024], w_site[1024], w_project_site[1024], w_app[1024];
    swprintf(w_stdlib,  1024, L"%s/python%s", app_path, py_version);
    swprintf(w_dynload, 1024, L"%s/python%s/lib-dynload", app_path, py_version);
    swprintf(w_project_site, 1024, L"%s/site-packages/{project_name}", app_path);
    swprintf(w_site,    1024, L"%s/site-packages", app_path);

    swprintf(w_app,     1024, L"%s", app_path);

    config.module_search_paths_set = 1;
    PyWideStringList_Append(&config.module_search_paths, w_stdlib);
    PyWideStringList_Append(&config.module_search_paths, w_dynload);
    PyWideStringList_Append(&config.module_search_paths, w_site);
    PyWideStringList_Append(&config.module_search_paths, w_project_site);
    PyWideStringList_Append(&config.module_search_paths, w_app);

    const char *native_lib_dir = getenv("ANDROID_NATIVE_LIB_DIR");
    if (native_lib_dir) {
        wchar_t w_native[1024];
        swprintf(w_native, 1024, L"%s", native_lib_dir);
        PyWideStringList_Append(&config.module_search_paths, w_native);
    }

    PyStatus status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) {
        LOGE("Service Py_Initialize failed");
        return 1;
    }

    PyRun_SimpleString(REDIRECT_STDIO);

    PyObject *runpy = PyImport_ImportModule("runpy");
    PyObject *func = PyObject_GetAttrString(runpy, "run_module");
    PyObject *args_tuple = PyTuple_Pack(1, PyUnicode_FromString(entrypoint));
    PyObject *kwargs = Py_BuildValue("{s:s, s:i}", "run_name", "__main__", "alter_sys", 1);

    PyObject *result = PyObject_Call(func, args_tuple, kwargs);

    int ret = 0;
    if (!result) {
        LOGE("python service entrypoint raised an exception");
        PyErr_Print();
        ret = 1;
    } else {
        Py_DECREF(result);
    }

    Py_FinalizeEx();

    (*env)->ReleaseStringUTFChars(env, j_androidPrivate, private_path);
    (*env)->ReleaseStringUTFChars(env, j_entrypoint, entrypoint);
    (*env)->ReleaseStringUTFChars(env, j_pyVersion, py_version);

    LOGI("Service python thread exit");
    return ret;
}
"""
        (cpp_dir / "service_main.c").write_text(content, encoding="utf-8")

    @staticmethod
    def write_cmake_lists(cpp_dir: Path) -> None:
        cpp_dir.mkdir(parents=True, exist_ok=True)
        content = """\
cmake_minimum_required(VERSION 3.22)
project(ksproject_main C)

set(CMAKE_C_STANDARD 11)

# SDL2 headers extracted from the SDL2 source tarball.
set(SDL2_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/sdl2_include")

# Python headers — per-ABI (each arch has its own pyconfig.h).
set(PYTHON_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/python_include/${ANDROID_ABI}")

# Pre-built shared libs live in jniLibs/<abi>/ alongside this build.
set(JNI_LIBS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}")

add_library(SDL2 SHARED IMPORTED)
set_target_properties(SDL2 PROPERTIES IMPORTED_LOCATION "${JNI_LIBS_DIR}/libSDL2.so")

add_library(python3 SHARED IMPORTED)
set_target_properties(python3 PROPERTIES IMPORTED_LOCATION "${JNI_LIBS_DIR}/libpython3.so")

# Primary UI Bootstrap
add_library(main SHARED main.c)
target_include_directories(main PRIVATE "${SDL2_INCLUDE_DIR}" "${PYTHON_INCLUDE_DIR}")
target_link_libraries(main SDL2 python3 log android)

# Background Service Bootstrap
add_library(service_main SHARED service_main.c)
target_include_directories(service_main PRIVATE "${PYTHON_INCLUDE_DIR}")
target_link_libraries(service_main python3 log android)
"""
        (cpp_dir / "CMakeLists.txt").write_text(content, encoding="utf-8")
